CREATE TABLE agent_session_state (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '自增主键',
  snapshot_id VARCHAR(64) NOT NULL COMMENT 'state 快照 ID',
  session_id VARCHAR(64) NOT NULL COMMENT 'session ID',
  state_version BIGINT NOT NULL COMMENT 'state 版本号，单 session 单调递增',
  task_goal VARCHAR(1024) DEFAULT NULL COMMENT '当前任务目标',
  state_json MEDIUMTEXT NOT NULL COMMENT '完整 state JSON',
  source_run_id VARCHAR(64) DEFAULT NULL COMMENT '本次 state 来源 run ID',
  created_at DATETIME NOT NULL COMMENT '创建时间',
  updated_at DATETIME NOT NULL COMMENT '更新时间',
  UNIQUE KEY uk_agent_session_state_snapshot_id (snapshot_id),
  UNIQUE KEY uk_agent_session_state_version (session_id, state_version),
  KEY idx_agent_session_state_session_id (session_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='session 结构化状态快照表';

CREATE TABLE agent_session_summary (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '自增主键',
  summary_id VARCHAR(64) NOT NULL COMMENT 'summary ID',
  session_id VARCHAR(64) NOT NULL COMMENT 'session ID',
  summary_version BIGINT NOT NULL COMMENT 'summary 版本号，单 session 单调递增',
  covered_from_sequence_no BIGINT NOT NULL COMMENT '覆盖起始 message sequence_no',
  covered_to_sequence_no BIGINT NOT NULL COMMENT '覆盖结束 message sequence_no',
  summary_text MEDIUMTEXT NOT NULL COMMENT '摘要正文',
  summary_template_key VARCHAR(128) NOT NULL COMMENT 'summary prompt 模板 key',
  summary_template_version VARCHAR(64) NOT NULL COMMENT 'summary prompt 模板版本',
  generator_provider VARCHAR(64) DEFAULT NULL COMMENT '生成 summary 的 provider',
  generator_model VARCHAR(128) DEFAULT NULL COMMENT '生成 summary 的 model',
  source_run_id VARCHAR(64) DEFAULT NULL COMMENT '触发本次 summary 的 run ID',
  created_at DATETIME NOT NULL COMMENT '创建时间',
  UNIQUE KEY uk_agent_session_summary_id (summary_id),
  UNIQUE KEY uk_agent_session_summary_version (session_id, summary_version),
  KEY idx_agent_session_summary_session_id (session_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='session 历史摘要表';

CREATE TABLE agent_memory_evidence (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '自增主键',
  evidence_id VARCHAR(64) NOT NULL COMMENT 'evidence ID',
  session_id VARCHAR(64) NOT NULL COMMENT 'session ID',
  turn_id VARCHAR(64) DEFAULT NULL COMMENT 'turn ID',
  run_id VARCHAR(64) DEFAULT NULL COMMENT 'run ID',
  target_type VARCHAR(64) NOT NULL COMMENT '目标类型',
  target_ref VARCHAR(128) NOT NULL COMMENT '目标对象 ID',
  target_field VARCHAR(255) DEFAULT NULL COMMENT '目标字段，如 state / summary / context 内的字段名',
  target_item_id VARCHAR(128) DEFAULT NULL COMMENT '目标字段内稳定条目 ID',
  display_path VARCHAR(255) DEFAULT NULL COMMENT '仅用于审计展示的目标路径',
  source_type VARCHAR(64) NOT NULL COMMENT '来源类型',
  message_id VARCHAR(64) DEFAULT NULL COMMENT '来源 message ID',
  tool_call_record_id VARCHAR(64) DEFAULT NULL COMMENT '来源 toolCallRecordId',
  working_context_snapshot_id VARCHAR(64) DEFAULT NULL COMMENT '来源 WorkingContextSnapshotId',
  internal_task_id VARCHAR(64) DEFAULT NULL COMMENT '来源 InternalTaskId',
  excerpt_text MEDIUMTEXT DEFAULT NULL COMMENT '证据摘录',
  confidence DECIMAL(6,4) DEFAULT NULL COMMENT '置信度',
  created_at DATETIME NOT NULL COMMENT '创建时间',
  UNIQUE KEY uk_agent_memory_evidence_id (evidence_id),
  KEY idx_agent_memory_evidence_session_id (session_id),
  KEY idx_agent_memory_evidence_target (target_type, target_ref),
  KEY idx_agent_memory_evidence_source_message (message_id),
  KEY idx_agent_memory_evidence_source_tool (tool_call_record_id),
  KEY idx_agent_memory_evidence_source_context (working_context_snapshot_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='state/summary/context 证据表';

CREATE TABLE agent_working_context_snapshot (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '自增主键',
  working_context_snapshot_id VARCHAR(64) NOT NULL COMMENT 'working context snapshot ID',
  conversation_id VARCHAR(64) NOT NULL COMMENT 'conversation ID',
  session_id VARCHAR(64) NOT NULL COMMENT 'session ID',
  turn_id VARCHAR(64) NOT NULL COMMENT 'turn ID',
  run_id VARCHAR(64) NOT NULL COMMENT 'run ID',
  context_build_seq INT NOT NULL COMMENT '当前 turn 内第几次构建上下文',
  model_call_sequence_no INT NOT NULL COMMENT '当前 turn 内第几次主模型调用',
  checkpoint_trigger VARCHAR(64) NOT NULL COMMENT '触发本次构建的 CheckpointTrigger',
  context_view_type VARCHAR(64) NOT NULL COMMENT '使用者视图类型',
  agent_mode VARCHAR(32) NOT NULL COMMENT '当前 agent 模式',
  transcript_snapshot_version BIGINT DEFAULT NULL COMMENT 'transcript 快照版本',
  working_set_version BIGINT DEFAULT NULL COMMENT 'working set 版本',
  state_version BIGINT DEFAULT NULL COMMENT 'state 版本',
  summary_version BIGINT DEFAULT NULL COMMENT 'summary 版本',
  budget_json MEDIUMTEXT NOT NULL COMMENT '预算快照 JSON',
  block_set_json MEDIUMTEXT NOT NULL COMMENT 'canonical block 集合 JSON',
  context_json MEDIUMTEXT NOT NULL COMMENT 'canonical WorkingContext JSON',
  projection_json MEDIUMTEXT NOT NULL COMMENT '最终 projection JSON',
  created_at DATETIME NOT NULL COMMENT '创建时间',
  UNIQUE KEY uk_agent_working_context_snapshot_id (working_context_snapshot_id),
  KEY idx_agent_working_context_turn (turn_id),
  KEY idx_agent_working_context_session (session_id),
  KEY idx_agent_working_context_run_seq (run_id, context_build_seq)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='working context 审计快照表';

CREATE TABLE agent_internal_llm_task (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '自增主键',
  internal_task_id VARCHAR(64) NOT NULL COMMENT '内部任务 ID',
  task_type VARCHAR(64) NOT NULL COMMENT '任务类型',
  session_id VARCHAR(64) NOT NULL COMMENT 'session ID',
  turn_id VARCHAR(64) DEFAULT NULL COMMENT 'turn ID',
  run_id VARCHAR(64) DEFAULT NULL COMMENT 'run ID',
  checkpoint_trigger VARCHAR(64) DEFAULT NULL COMMENT '触发本次任务的 checkpoint trigger',
  prompt_template_key VARCHAR(128) NOT NULL COMMENT '模板 key',
  prompt_template_version VARCHAR(64) NOT NULL COMMENT '模板版本',
  request_json MEDIUMTEXT NOT NULL COMMENT '内部任务请求 JSON',
  response_json MEDIUMTEXT DEFAULT NULL COMMENT '内部任务响应 JSON',
  status VARCHAR(32) NOT NULL COMMENT 'PENDING/RUNNING/SUCCEEDED/FAILED/DEGRADED/SKIPPED',
  error_code VARCHAR(64) DEFAULT NULL COMMENT '错误码',
  error_message VARCHAR(1024) DEFAULT NULL COMMENT '错误消息',
  duration_ms BIGINT DEFAULT NULL COMMENT '执行耗时',
  created_at DATETIME NOT NULL COMMENT '创建时间',
  completed_at DATETIME DEFAULT NULL COMMENT '完成时间',
  UNIQUE KEY uk_agent_internal_llm_task_id (internal_task_id),
  KEY idx_agent_internal_llm_task_session (session_id),
  KEY idx_agent_internal_llm_task_turn (turn_id),
  KEY idx_agent_internal_llm_task_run (run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='内部 LLM 任务审计表';
